### ISSUE TITLE
Issue with cache invalidation on production deployment

### ISSUE THREAD

**Issue by cscairns** [18F/myra#139]
Production deployment changes aren't propagating within 1-hour clock.

**Comment by konklone** [comment]
OK. This is not one of the higher points of my career.

The cache time I've been setting (and which I used in docs that give you the command to paste) is wrong. 86400 seconds is 1 day. We have been trying to set 1 hour. That's 3600 seconds.

**Comment by cscairns** [comment]
Well, at least it was a simple fix.
